### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by seppelicous** [aharren/ios-energy-widget#1]
Hi, 
thank you very much for sharing this script - looks very nice so far.
I just have some trouble with my code. I already use influx & grafana about 2 years and I am not sure if I have the correct data setup.

I filled url, apikey and the database and edited the queries with my measurements.
Now I get this error:
`Error on line 154:32: TypeError: undefined is not an object (evaluating 'element.series[0]')`

I appreciate your support!
kind regards

**Comment by aharren** [comment]
Hi,

it looks like something in the queries is wrong.

Can you add a log statement for the full response, please? Just before line 154:

```
console.log('response: ' + JSON.stringify(response, null, 2));
```

Best regards, Arne

**Comment by seppelicous** [comment]
Sure, and here is the result:

`response: {
  "results": [
    {
      "error": "not executed",
      "statement_id": 0
    }
  ]
}
Error on line 157:32: TypeError: undefined is not an object (evaluating 'element.series[0]') `

**Comment by aharren** [comment]
If I remember correctly, then this means that the first query was not executed due to an error in one of the other queries. But, the error is not shown.

Can you comment (`//`) all the query elements in the configuration (lines 39, 45, 53, 59, 63). And then remove the comment for the first one, run the script, and check the response log output if it is OK and contains the series result? If it is OK, then add the comment again and try it with the second query. Such that you always run a single query.

**Comment by seppelicous** [comment]
Thank you very much of the support. It is working now! The issue was a wrong database and a wrong dataname in the first query.
