### ISSUE TITLE
Could you please share an example of the data file, just for purposes of standalone offline development? 

### ISSUE THREAD

**Issue by edalessio** [aharren/ios-energy-widget#2]
This project is wonderful!  I'd like to try to run it, but I don't have a Grafna DB or data file to use.  Could you please share a data file?

**Comment by aharren** [comment]
I've created a new branch with an example data file and some small changes to load the file from your local disk instead of a web server: https://github.com/aharren/ios-energy-widget/tree/example-data-file - the file is in the example folder.

You can view the configured example widget and the example data file with the following commands:

```
node dev/server.js example/widget.js medium 'style=1'
```

It will show a blank widget in your browser on first start.
Then copy the example data file to the `.fs/documents` folder, which was created by starting the `server.js` file:
```
cp example/data.json .fs/documents 
```

Now refresh the widget page in your browser and it will render the example data.
